### ISSUE TITLE
is their a way to saved meta data externally on MySQL database?

### ISSUE THREAD

**Issue by animeesh** [callmesora/DeepStream-TrackerEval#2]
I am very much fascinated with your "Traffic Analytics using custom NVIDIA DeepStream and YOLOv4" project i am planning to do similar kind of project where I need to send meta data into SQL database. but unable to kind similar kind or resource or help to do so.

**Comment by callmesora** [comment]
Yeah you can process the metadata to that SQL database. I haven't messed around too much with DeepStream metadata, I was working mostly on the configs themselves so I cannot help you too much on this regard

In my repo here, you can see how to extract this metadata https://github.com/callmesora/DeepStream-TrackerEval

If you need to stream this data to a database perhaps consider Kafka topic or something . 
ChatGPT is your friend here :)

**Comment by callmesora** [comment]
Here is an example on how to process the metadata in python (Keep in mind my repo is in C++ so you might have to do some workarounds here)

```
import mysql.connector

# Connect to the MySQL database
cnx = mysql.connector.connect(user='your_username', 
                              password='your_password',
                              host='your_host',
                              database='your_database')
cursor = cnx.cursor()

# Insert the metadata into the database
def save_metadata(metadata):
    add_metadata = ('INSERT INTO metadata '
                   '(timestamp, object_class, confidence, xmin, ymin, xmax, ymax) '
                   'VALUES (%s, %s, %s, %s, %s, %s, %s)')
    data_metadata = (metadata['timestamp'], metadata['object_class'], metadata['confidence'], metadata['xmin'], metadata['ymin'], metadata['xmax'], metadata['ymax'])
    cursor.execute(add_metadata, data_metadata)
    cnx.commit()

# Use the function to save the metadata
metadata = {'timestamp': '2022-01-01 12:00:00', 'object_class': 'car', 'confidence': 0.9, 'xmin': 0, 'ymin': 0, 'xmax': 100, 'ymax': 100}
save_metadata(metadata)

# Close the cursor and connection
cursor.close()
cnx.close()

```

If you use the txt file DeepStream saves with the metadata and write a Python script to parse it in this format (You can ask ChatGPT for this script) then you can use link these two scripts to populate your database ,

Wish I could help more
